### ISSUE TITLE
Link for the tutorial doesn't exist anymore

### ISSUE THREAD

**Issue by f03n1x** [vilbeyli/TrajectoryTutorial#1]
Hi Volkan first off I'd like to say thank you so much for making this tutorial, it is really quite helpful.

Sadly though the link https://vilbeyli.github.io/Projectile-Motion-Tutorial-for-Arrows-and-Missiles-in-Unity3D/ doesn't work anymore, hopefully you can fix it!

**Comment by vilbeyli** [comment]
Hey Mark,

Thank you for reporting this. I realized I have recently accidentally nuked my entire website lol. I'm working on getting it back, will update once I fix it.

**Comment by vilbeyli** [comment]
should be fixed, closing the issue
